version: 2.1
orbs:
  windows: circleci/windows@2.2.0
jobs:
  build:
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: Install .NET 7.0
          command: |
            choco install dotnet-sdk --version=7.0.400 -y
      - run:
          name: Install dependencies
          command: dotnet restore
      - run:
          name: Build application
          command: dotnet build --configuration Release
      - run:
          name: Publish application
          command: |
            dotnet publish --configuration Release /p:PublishProfile="Properties/PublishProfiles/CircleCI - Web Deploy.pubxml" /p:Password=$DEPLOY_PASSWORD
workflows:
  build_and_deploy:
    jobs:
      - build
