version: 2.1
orbs:
  windows: circleci/windows@2.2.0
jobs:
  build:
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: Print environment variables
          command: env
workflows:
  build_and_deploy:
    jobs:
      - build
