version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print environment variables
          command: env
workflows:
  build_and_deploy:
    jobs:
      - build